// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxIc3_FtlJmVCJ6eZ0UNSTzYguSWrjLYM',
    appId: '1:107759772344:web:38db611d00dd8b5ff38a4d',
    messagingSenderId: '107759772344',
    projectId: 'student-1de80',
    authDomain: 'student-1de80.firebaseapp.com',
    storageBucket: 'student-1de80.appspot.com',
    measurementId: 'G-HHJ979B41N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWICtSFdP1pAhgkjHhgJJ-2RktaH2ZprY',
    appId: '1:107759772344:android:edbf9e5cfac532c8f38a4d',
    messagingSenderId: '107759772344',
    projectId: 'student-1de80',
    storageBucket: 'student-1de80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmYf6FjsiWHxTBN8ly1rXoJbbf5EJCz7w',
    appId: '1:107759772344:ios:93bb376b7d87908ff38a4d',
    messagingSenderId: '107759772344',
    projectId: 'student-1de80',
    storageBucket: 'student-1de80.appspot.com',
    iosBundleId: 'com.example.blocMiniProjectHive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmYf6FjsiWHxTBN8ly1rXoJbbf5EJCz7w',
    appId: '1:107759772344:ios:62a0eab103bb1732f38a4d',
    messagingSenderId: '107759772344',
    projectId: 'student-1de80',
    storageBucket: 'student-1de80.appspot.com',
    iosBundleId: 'com.example.blocMiniProjectHive.RunnerTests',
  );
}
